// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFX2zfGta3Bzr_vLpFLN2yWhUGcCKouNU',
    appId: '1:853035020452:web:14af9ec0d5b5e62c7d3631',
    messagingSenderId: '853035020452',
    projectId: 'minirater',
    authDomain: 'minirater.firebaseapp.com',
    storageBucket: 'minirater.appspot.com',
    measurementId: 'G-Y9X0W6QEZR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAf4AqgO2oYRmViZJxDnrmYT-0IWJcYos0',
    appId: '1:853035020452:android:d168d9f867f0ecdd7d3631',
    messagingSenderId: '853035020452',
    projectId: 'minirater',
    storageBucket: 'minirater.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBovvIGwQ9pyZdBxOPJ6Imc4CRKKDbChJs',
    appId: '1:853035020452:ios:bdaf68f57fbd7e727d3631',
    messagingSenderId: '853035020452',
    projectId: 'minirater',
    storageBucket: 'minirater.appspot.com',
    iosClientId: '853035020452-8q01g8j9oe1vhq3sjd597gvq6pscgijl.apps.googleusercontent.com',
    iosBundleId: 'com.example.minirater',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBovvIGwQ9pyZdBxOPJ6Imc4CRKKDbChJs',
    appId: '1:853035020452:ios:bdaf68f57fbd7e727d3631',
    messagingSenderId: '853035020452',
    projectId: 'minirater',
    storageBucket: 'minirater.appspot.com',
    iosClientId: '853035020452-8q01g8j9oe1vhq3sjd597gvq6pscgijl.apps.googleusercontent.com',
    iosBundleId: 'com.example.minirater',
  );
}
